export const WSMethods = {
  connection: 'connecton',
  createRoom: 'createRoom',
  removeRoom: 'removeRoom',
  addMember: 'addMember',
  removeMember: 'removeMember',
  addIssue: 'addIssue',
  removeIssue: 'removeIssue',
  changeSettings: 'changeSettings',
  roomKey: 'roomKey',
  error: 'error',
  changeRoute: 'changeRoute',
  setActiveIssue: 'setActiveIssue',
  setVoice: 'setVoice',
  resetRound: 'resetRound',
  updateGame: 'updateGame',
};
