export const WSMethods = {
  connection: 'connecton',
  createRoom: 'createRoom',
  removeRoom: 'removeRoom',
  addMember: 'addMember',
  removeMember: 'removeMember',
  addIssue: 'addIssue',
  changeIssue: 'changeIssue',
  removeIssue: 'removeIssue',
  changeSettings: 'changeSettings',
  roomKey: 'roomKey',
  error: 'error',
  changeRoute: 'changeRoute',
  startKickUserVoting: 'startKickUserVoting',
  resetKickUserVoting: 'resetKickUserVoting',
};
